### ISSUE TITLE
License Mismatch

### ISSUE THREAD

**Issue by TechnologyClassroom** [mkazin/ansible-logLastLine#1]
I noticed you have a mismatched license on this project.

[README.md](https://github.com/mkazin/ansible-logLastLine/blob/needs_testing/README.md) says BSD and [LICENSE](https://github.com/mkazin/ansible-logLastLine/blob/needs_testing/LICENSE) says MIT.

**Comment by mkazin** [comment]
Good catch. Fixed the Readme file. Thanks! 👍 

I really should test this and merge it in one of these days. I recently ported it to zsh and should share that.
